[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
optimizer = true
optimizer-runs = 10_000
verbosity = 3
evm_version = "cancun"
fs_permissions = [
  { access = "read-write", path = "./deployments" }
]

ignored_warnings_from = ["lib", "test", "script"]

no_match_coverage = "script|test|src/bridges/hyperlane/libs/"

[fmt]
bracket_spacing = true
line_length = 130
single_line_statement_block = "single"
multiline_func_header = "params_first_multi"

[rpc_endpoints]
ethereum = "${ETHEREUM_RPC}"
hyperevm = "${HYPEREVM_RPC}"
sepolia = "${SEPOLIA_RPC}"
hyperevm_testnet = "${HYPEREVM_TESTNET_RPC}"

[etherscan]
ethereum = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/api" }
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }